server:
  port: 3033



#Eureka注册中心配置
spring:
  application:
    name: feign-server-provider
  cloud:
    #sentinel
    sentinel:
      eager: true
      transport:
        dashboard: localhost:8080
        port: 8719

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

